### Lab Task 1

In [1]:
"""
Create a simple list containing the characters of the word: MANIPULATOR. Loop through the list and display each character on a new line.
"""

name_list = ["M", "A", "N", "I", "P", "U", "L", "A", "T", "O", "R"]

for character in name_list:
    print(f"{character}")

M
A
N
I
P
U
L
A
T
O
R


### Lab Task 2

In [2]:
"""
Write a program which first prompts the user for an integer which will be the size of a list. Then, the program must repeatedly prompt the user to input the items of the list. Each item is to be added with the append function. The inputs continue until the number of items reach the size of the list. The final list is then printed. The syntax for making an empty list and appending function are given below:

my_list = [ ]
my_list.append(item)
"""

size = int(input("Enter the size of the list: "))
number_list = []
count = 0

while count < size:
    item = input("Enter an input: ")
    number_list.append(item)
    count += 1

print(number_list)

Enter the size of the list:  4
Enter an input:  2
Enter an input:  3
Enter an input:  7
Enter an input:  3


['2', '3', '7', '3']


### Lab Task 3

In [3]:
"""
Write a function that takes in a list input and returns true if the items of the list make a palindrome. A palindrome is a word/number that is written the same way forward and backward. Examples of palindromes include “radar”, “level”, “5445”, “8395938”, “racecar”. To use a list in a function, use the following syntax:

def my_function(my_list):
	statement1
	statement2

"""

def palindrome_check(my_list):
    if my_list == my_list[::-1]:
        return True
    else:
        return False
    
test_word = input("Enter a word: ")
if palindrome_check(list(test_word)):
    print(f"Input '{test_word}' is a palindrome.")
else:
    print(f"Input '{test_word}' is not a palindrome.")

Enter a word:  racecar


Input 'racecar' is a palindrome.


### Lab Task 4

In [4]:
"""
Write a program that repeatedly prompts the user for input. The user will keep entering numbers which are added to a list. Each time a number is added to the list, it must be placed in such a way that the list items are always in ascending order. Each time a number is input, the list is to be printed showing the newly added number. This continues until the word “done” is input at which point the prompts will stop. The final list is then displayed. Do NOT use any inbuilt sorting function for this task.
"""

number_list = []

while True:
    number = input("Enter an input: ")
    if number == "done":
        break
    else:
        number = int(number)
        for index, item in enumerate(number_list):
            if number < item:
                number_list.insert(index, number)
                break
        else:
            number_list.append(number)
        print(number_list)

Enter an input:  4


[4]


Enter an input:  9


[4, 9]


Enter an input:  8


[4, 8, 9]


Enter an input:  6


[4, 6, 8, 9]


Enter an input:  done


### Lab Task 5

In [5]:
"""
In this task, you will implement the Selection Sort algorithm using lists. A selection sort searches a list looking for the smallest element. Then, the smallest element is swapped with the first element of the list. The process is repeated for the sub-list beginning with the second element of the list. Each pass of the list results in one element being placed in its proper location. When the sub-list being processed contains one element, the list is sorted. Create a function which takes a list as input and then implements the selection sort on it. You need to print the list each time a swap is made.
"""

my_list = [5, 11, 8, 6, 7, 2]
print(f"Original list: {my_list}\n")

for i in range(len(my_list)):
    smallest_index = i
    for j in range(i+1, len(my_list)):
        if my_list[j] < my_list[smallest_index]:
            smallest_index = j
    my_list[smallest_index], my_list[i] = my_list[i], my_list[smallest_index]
    print("List after pass: ", my_list)

Original list: [5, 11, 8, 6, 7, 2]

List after pass:  [2, 11, 8, 6, 7, 5]
List after pass:  [2, 5, 8, 6, 7, 11]
List after pass:  [2, 5, 6, 8, 7, 11]
List after pass:  [2, 5, 6, 7, 8, 11]
List after pass:  [2, 5, 6, 7, 8, 11]
List after pass:  [2, 5, 6, 7, 8, 11]


### Lab Task 6

In [8]:
"""
Use the np.array function to define two matrices of size 3x3. Place numerical elements of your choice in the matrices. Write code to perform the following:
•	Print the arrays
•	Compute the sum of the matrices
•	Compute the difference of the matrices
•	Compute the element-wise product of the matrices
•	Compute the element-wise division of the matrices
•	Compute the matrix multiplication of the matrices
"""

import numpy as np

arr_1 = np.random.randint(1, 10, (3, 3))
arr_2 = np.random.randint(1, 10, (3, 3))

print("Sum of Matrices: \n", arr_1 + arr_2)
print("\nDifference of Matrices: \n", arr_1 - arr_2)
print("\nElement-wise Product of Matrices: \n", arr_1 * arr_2)
print("\nElement-wise Division of Matrices: \n", arr_1 / arr_2)
print("\nMatrix Multiplication of Matrices: \n", arr_1 @ arr_2)

Sum of Matrices: 
 [[12  9 17]
 [12 14 13]
 [17 15 11]]

Difference of Matrices: 
 [[ 6 -7  1]
 [-6  2  1]
 [ 1  1 -5]]

Element-wise Product of Matrices: 
 [[27  8 72]
 [27 48 42]
 [72 56 24]]

Element-wise Division of Matrices: 
 [[3.         0.125      1.125     ]
 [0.33333333 1.33333333 1.16666667]
 [1.125      1.14285714 0.375     ]]

Matrix Multiplication of Matrices: 
 [[108 141 150]
 [137 121 128]
 [123 141 144]]
