### Lab Task 1

In [1]:
"""
Create a 1-D list containing the characters of the name of any one person in your group. Loop through the list and display each character on a new line.
"""

name_list = ["M", "u", "h", "a", "m", "m", "a", "d", " ", "U", "m", "e", "r"]

for character in name_list:
    print(f"{character}")

M
u
h
a
m
m
a
d
 
U
m
e
r


### Lab Task 2

In [2]:
"""
Write a program that repeatedly prompts the user for input. The user will keep entering numbers which are added to a list. Each time a number is added to the list, it must be placed in such a way that the list items are always in ascending order. Each time a number is input, the list is to be printed showing the newly added number. This continues until the word “done” is input at which point the prompts will stop. The final list is then displayed. Do NOT use any inbuilt sorting function for this task.
"""

number_list = []

while True:
    number = input("Enter an input: ")
    if number == "done":
        break
    else:
        number = int(number)
        for index, item in enumerate(number_list):
            if number < item:
                number_list.insert(index, number)
                break
        else:
            number_list.append(number)
        print(number_list)

Enter an input:  4


[4]


Enter an input:  7


[4, 7]


Enter an input:  3


[3, 4, 7]


Enter an input:  done


### Lab Task 3

In [3]:
"""
Create a list with the sequence 1, 2, 3… 20. Then using the slice operation (:) on this list, print the following sub-lists:
5, 6, 7… 20
1, 2, 3… 12
7, 8, 9 … 16
4, 5
11, 12, 13, 14
"""

main_list = list(range(1, 20+1))

print("Sub-list 1: ", main_list[4:])
print("Sub-list 2: ", main_list[0:12])
print("Sub-list 3: ", main_list[6:16])
print("Sub-list 4: ", main_list[3:5])
print("Sub-list 5: ", main_list[10:14])

Sub-list 1:  [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Sub-list 2:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Sub-list 3:  [7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Sub-list 4:  [4, 5]
Sub-list 5:  [11, 12, 13, 14]


### Lab Task 4

In [4]:
"""
In this task, you will make use of dictionaries. Write a program that first prompts the user to input five strings which will be the keys of the dictionary. Then, the program must prompt the user to input the values of the respective keys. When entering the values, the user must be shown the key whose value is being input. Once all values are entered, display the dictionary. 
"""

# create an empty dictionary
task_dict = {}

# prompt the user to input five keys
for i in range(5):
    key = input("Enter key " + str(i + 1) + ": ")
    task_dict[key] = None

# prompt the user to input values for each key
for key in task_dict:
    value = input("Enter value for " + key + ": ")
    task_dict[key] = value

# display the dictionary
print(task_dict)

Enter key 1:  one
Enter key 2:  two
Enter key 3:  three
Enter key 4:  four
Enter key 5:  five
Enter value for one:  1
Enter value for two:  2
Enter value for three:  3
Enter value for four:  4
Enter value for five:  5


{'one': '1', 'two': '2', 'three': '3', 'four': '4', 'five': '5'}


### Lab Task 5

In [2]:
"""
Import the NumPy Library. Use the np.array function to define a 5x5 array with elements of your choice. Ensure that the elements are numbers (not strings). Then, perform the following:
•	Print the array
•	Print element(4, 4)
•	Print rows 2 and 3 via slicing
•	Print the central 3x3 elements in a matrix
•	Compute the sum of the matrix elements
•	Compute the sum of the matrix elements along axis 0
•	Compute the sum of the matrix elements along axis 1
•	Compute the mean of the matrix elements
•	Compute the standard deviation of the matrix elements
"""

import numpy as np
arr = np.random.randint(1, 10, (5, 5))

print("Array: \n", arr)
print("\nElement (4, 4): ", arr[3, 3])
print("\nRows 2 and 3: \n", arr[1:3, :])
print("\nCentral 2x3 Elements: \n", arr[1:4, 1:4])
print("\nSum of Matrix Elements: ", np.sum(arr))
print("\nSum of Matrix Elements along Axis 0: ", np.sum(arr, axis=0))
print("\nSum of Matrix Elements along Axis 1: ", np.sum(arr, axis=1))
print("\nMean of Matrix Elements: ", np.mean(arr))
print("\nStandard Deviation of Matrix Elements: ", np.std(arr))

Array: 
 [[9 5 2 2 3]
 [1 8 3 5 6]
 [9 1 9 4 9]
 [4 1 2 3 9]
 [2 3 9 6 9]]

Element (4, 4):  3

Rows 2 and 3: 
 [[1 8 3 5 6]
 [9 1 9 4 9]]

Central 2x3 Elements: 
 [[8 3 5]
 [1 9 4]
 [1 2 3]]

Sum of Matrix Elements:  124

Sum of Matrix Elements along Axis 0:  [25 18 25 20 36]

Sum of Matrix Elements along Axis 1:  [21 23 32 19 29]

Mean of Matrix Elements:  4.96

Standard Deviation of Matrix Elements:  2.9997333214804276


### Lab Task 6

In [3]:
"""
Use the np.array function to define two matrices of size 3x3. Place numerical elements of your choice in the matrices. Write code to perform the following:
•	Print the arrays
•	Compute the sum of the matrices
•	Compute the difference of the matrices
•	Compute the element-wise product of the matrices
•	Compute the element-wise division of the matrices
•	Compute the matrix multiplication of the matrices
"""

arr_1 = np.random.randint(1, 10, (3, 3))
arr_2 = np.random.randint(1, 10, (3, 3))

print("Sum of Matrices: \n", arr_1 + arr_2)
print("\nDifference of Matrices: \n", arr_1 - arr_2)
print("\nElement-wise Product of Matrices: \n", arr_1 * arr_2)
print("\nElement-wise Division of Matrices: \n", arr_1 / arr_2)
print("\nMatrix Multiplication of Matrices: \n", arr_1 @ arr_2)

Sum of Matrices: 
 [[13  6  6]
 [10 14 10]
 [10 10 11]]

Difference of Matrices: 
 [[ 5  2 -4]
 [ 0  4 -8]
 [ 6 -2  7]]

Element-wise Product of Matrices: 
 [[36  8  5]
 [25 45  9]
 [16 24 18]]

Element-wise Division of Matrices: 
 [[2.25       2.         0.2       ]
 [1.         1.8        0.11111111]
 [4.         0.66666667 4.5       ]]

Matrix Multiplication of Matrices: 
 [[ 58  44  83]
 [ 67  61 108]
 [ 70  90  94]]


### Lab Task 7

In [7]:
"""
In this task, you will use various functions of the SciPy library that are commonly used in machine learning. Import the various modules from SciPy Library:
from scipy.optimize import root
from scipy.optimize import minimize
from scipy.sparse import csr_matrix
from scipy.interpolate import interp1d

a)	Use the root function to determine the roots of the equation 3x2 + 2x – 10.
b)	In machine learning, it is very often required to find the argument that minimizes a complex equation with the given data. Use the minimize function to determine the roots of the equation x2 - 20x + 45.
c)	In machine learning, sometimes there are matrices in which most of the elements are zero. In such cases, it is more convenient to store them as sparse matrices which holds information of the non-zero elements. In this task, create a 3x10 sparse matrix (A) with elements of your choice. Ensure that about 2/3 of the elements are zero. Then, print the matrix information using csr_matrix(A), csr_matrix(A).data and csr_matrix(A).count_nonzero().
d)	In this task, you will perform interpolation. Create two lists x and y. The list x contains elements 1,2,3… 10. The list y contains the elements for y = 2x + 1. Use the interp_func = interp1d(x, y) to get the interpolating function. Then, use interp_func(val) to get any 3 interpolated values.
"""

from scipy.optimize import root
from scipy.optimize import minimize
from scipy.sparse import csr_matrix
from scipy.interpolate import interp1d

# a)
equation = lambda x: 3*x**2 + 2*x - 10
root_eqn = root(equation, 0)
print("a)")
print(r"Roots of Equation 3x^2 + 2x - 10: ", root_eqn.x)
print(f"Value at {root_eqn.x}: ", equation(root_eqn.x))

# b)
equation = lambda x: x**2 - 20*x + 45
print("\nb)")
root_eqn = minimize(equation, 0)
print(r"Roots of Equation x^2 - 20x + 45: ", root_eqn.x)
print(f"Value at {root_eqn.x}: ", equation(root_eqn.x))

# c)
print("\nc)")
arr = np.array([[1, 0, 0, 0, 0, 0, 3, 0, 0, 0],
              [2, 0, 0, 0, 0, 0, 0, 0, 8, 0],
              [3, 0, 0, 0, 0, 5, 0, 0, 0, 0]])

sparse_arr = csr_matrix(arr)
print("Sparse Matrix: \n", sparse_arr)
print("\nSparse Matrix Data: \n", sparse_arr.data)
print("\nSparse Matrix Non-Zero Elements: \n", sparse_arr.count_nonzero())

# d)
print("\nd)")
x = list(range(1, 10+1))
y = [(2*i) + 1 for i in x]
print("\nx = ", x)
print("y = ", y)

interp_fun = interp1d(x, y)
interp_fun_val = interp_fun([1.5, 2.5, 3.5])

print("\nInterpolated Values at: ", [1.5, 2.5, 3.5], "\n\t\t\t", interp_fun_val)

a)
Roots of Equation 3x^2 + 2x - 10:  [1.52258812]
Value at [1.52258812]:  [0.]

b)
Roots of Equation x^2 - 20x + 45:  [10.00000017]
Value at [10.00000017]:  [-55.]

c)
Sparse Matrix: 
   (0, 0)	1
  (0, 6)	3
  (1, 0)	2
  (1, 8)	8
  (2, 0)	3
  (2, 5)	5

Sparse Matrix Data: 
 [1 3 2 8 3 5]

Sparse Matrix Non-Zero Elements: 
 6

d)

x =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y =  [3, 5, 7, 9, 11, 13, 15, 17, 19, 21]

Interpolated Values at:  [1.5, 2.5, 3.5] 
			 [4. 6. 8.]
